import React, { useState } from 'react'
import useFirestoreBySearch from '../../hooks/useFireStoreBySearch';
import { useRouter } from 'next/router';
import Head from 'next/head';
import NavBar from '../../components/nav';
import AppButton from '../../components/AppButton';
import ItemCard from './../../components/ItemCard';
import LoadingAnimation from '../../components/LoadingAnimation';
import ItemListCard from '../../components/ItemListCard';
import { ViewType } from '../../types';
import { HiMenu } from 'react-icons/hi';
import { IoGridOutline } from 'react-icons/io5';

const ItemDetails = () => {

  const router = useRouter();
  const { docs, loading } = useFirestoreBySearch('items', router.query.itemId);
  const [viewType, setViewType] = useState<ViewType>(ViewType.GRID);
  const [extended, setExtended] = useState<string>('');

  function handleClick(){
    router.push('/add-item');
  }

  return (
    <>
      <Head>
        <title>Item Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className='min-h-[calc(100vh-5rem)] bg-slate-600 w-full flex items-center flex-col text-white'>
        {loading ?
          <LoadingAnimation />
          : 
          docs.length === 0 ? 
            <div className='w-60'>
              <p className='text-center text-xl'>Item not found</p>
              <AppButton text='Add Item' disabled={false} onClick={handleClick} />
              <button
                onClick={()=>router.push('/home')}
                className='px-4 py-2 bg-slate-500 shadow-lg text-white hover:scale-105 active:scale-95 disabled:opacity-50 rounded w-full'
              >
                Back
              </button>
            </div>
            :
            <div className='py-5 px-10 w-full'>
              <div className='flex items-center justify-between px-2 py-2'>
                <p className='text-lg pb-2'>Search Result : {docs.length}</p>
                <div className='flex items-center'>
                  <button className='hidden md:block' onClick={()=>setViewType(ViewType.LIST)}>
                    <HiMenu style={viewType === ViewType.LIST ? {background: '#ffffff80', padding: 5, borderRadius: 5} : {padding: 5}} size={40} />
                  </button>
                  <button onClick={()=>setViewType(ViewType.GRID)}>
                    <IoGridOutline style={viewType === ViewType.GRID ? {background: '#ffffff80', padding: 5, borderRadius: 5} : {padding: 5}} size={40} />
                  </button>
                </div>
              </div>
              <div className='flex flex-wrap items-center justify-center'>
              {docs.map(doc => {
                  if (viewType === ViewType.GRID) return <ItemCard key={doc.id} data={doc} />
                  else return <ItemListCard key={doc.id} data={doc} extended={extended} setExtended={setExtended} />
                })}
              </div>
            </div>
        }
      </div>
    </>
  )
}

export default ItemDetails;