import React from 'react'
import useFirestoreBySearch from '../../hooks/useFireStoreBySearch';
import { useRouter } from 'next/router';
import Head from 'next/head';
import NavBar from '../../components/nav';
import AppButton from '../../components/AppButton';
import ItemCard from './../../components/ItemCard';
import LoadingAnimation from '../../components/LoadingAnimation';

const ItemDetails = () => {

  const router = useRouter();
  const { docs, loading } = useFirestoreBySearch('items', router.query.itemId);

  function handleClick(){
    router.push('/add-item');
  }

  return (
    <>
      <Head>
        <title>Item Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className='min-h-[calc(100vh-5rem)] bg-slate-600 flex items-center justify-center flex-col text-white'>
        {loading ?
          <LoadingAnimation />
          : 
          docs.length === 0 ? 
            <div className='w-60'>
              <p className='text-center text-xl'>Item not found</p>
              <AppButton text='Add Item' disabled={false} onClick={handleClick} />
              <button
                onClick={()=>router.push('/home')}
                className='px-4 py-2 bg-slate-500 shadow-lg text-white hover:scale-105 active:scale-95 disabled:opacity-50 rounded w-full'
              >
                Back
              </button>
            </div>
            :
            <div className='py-5'>
              <p className='text-center text-lg pb-2'>Search Result : {docs.length}</p>
              <div className='flex flex-wrap items-center justify-center'>
                {docs.map(doc => (
                  <ItemCard key={doc.id} data={doc} />
                ))}
              </div>
            </div>
        }
      </div>
    </>
  )
}

export default ItemDetails;