import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router';
import { useState } from 'react';
import AppButton from '../components/AppButton';
import AppInput from '../components/AppInput';
import NavBar from './../components/nav';

const Home: NextPage = () => {

  const router = useRouter();
  const [searchId, setSearchId] = useState('');

  function handleClick(){
    router.push(`/item-details/${searchId}`)
  }

  return (
    <>
      <Head>
        <title>Stock Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className='min-h-[calc(100vh-5rem)] bg-slate-600 flex items-center justify-center flex-col text-white'>
        <div className='w-60'>
          <AppInput label='Search by id :' placeholder='Item id...' value={searchId} onChange={setSearchId} />
          <AppButton text='search' disabled={!searchId} onClick={handleClick} />
        </div>
      </div>
    </>
  )
}

export default Home
