import Head from 'next/head';
import React from 'react';
import LoadingAnimation from '../components/LoadingAnimation';
import NavBar from '../components/nav';
import useFirestore from '../hooks/useFirestore';
import ItemCard from './../components/ItemCard';

const Items: React.FC = () => {

  const { docs, loading } = useFirestore('items');

  return (
    <>
      <Head>
        <title>All Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className='min-h-[calc(100vh-5rem)] bg-slate-600 flex items-center justify-center flex-col text-white'>
        {loading ?
          <LoadingAnimation />
          : 
          docs.length > 0 ?
            <div className='py-5'>
              <p className='text-center text-lg pb-2'>Search Result : {docs.length}</p>
              <div className='flex flex-wrap items-center justify-center'>
                {docs.map(doc => (
                  <ItemCard key={doc.id} data={doc} />
                ))}
              </div>
            </div>
            :
            <p className='text-center text-lg'>no items found</p>
        }
      </div>
    </>
  );
};

export default Items;